def image
pipeline {
    agent any
    environment {
        DOCKER_URL = 'docker-release.cckuo.ee.ntust.edu.tw'
        PROJECT_PATH = 'sps/taipower-project'
        PROJECT_NAME = 'vue-taipower'
        PROJECT_TAG = 'latest'
    }
    stages {
        stage('Build') {
            steps {
                script {
                    image = docker.build("${DOCKER_URL}/${PROJECT_PATH}/${PROJECT_NAME}:${PROJECT_TAG}")
                }
                sh 'docker image prune -f'
                sh 'docker image ls'
            }
        }
        /*stage('Test') {
            steps {
                script {
                    sh "docker run\
                    --rm\
                    -d\
                    -p 19999:8080\
                    --name ${env.PROJECT_NAME}\
                    ${env.DOCKER_URL}/${env.PROJECT_PATH}/${PROJECT_NAME}:${env.PROJECT_TAG}\
                    /bin/sh jenkins-test.sh && curl localhost:19999"
                }
                script {
                    sh "docker stop ${env.PROJECT_NAME}"
                }
            }
        }*/
        stage('Docker Push') {
            steps {
                script {
                    withDockerRegistry(credentialsId: 'CCKUO-NEXUS', url: 'https://docker-release.cckuo.ee.ntust.edu.tw') {
                        image.push()
                    }
                }
            }
        }
    }
    post {
        success {
            mattermostSend (
            color: "#5FB15F",
            channel: 'jenkins-status-bot',
            endpoint: 'https://chat.cckuo.ee.ntust.edu.tw/hooks/gorps4ihgin6jr5pfwbgass3na',
            message: "Build success: ${env.JOB_NAME} #${env.BUILD_NUMBER} (<${env.BUILD_URL}|Link to build>)"
            )
        }
        failure {
            mattermostSend (
            color: '#FF0000',
            channel: 'jenkins-status-bot',
            endpoint: 'https://chat.cckuo.ee.ntust.edu.tw/hooks/gorps4ihgin6jr5pfwbgass3na',
            message: "Build fail: ${env.JOB_NAME} #${env.BUILD_NUMBER} (<${env.BUILD_URL}|Link to build>)"
            )
        }
    }
}

